import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Layout from "@/common/layout";
import ApolloHeaderSettingLocalStorage from "@/common/settings/apollo-header-setting";

const NSN = localFont({
  src: "../../public/fonts/NanumSquareNeo-bRg.ttf",
  variable: "--NSN",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${NSN.variable}`}>
        <ApolloHeaderSettingLocalStorage>
          <Layout>{children}</Layout>
        </ApolloHeaderSettingLocalStorage>
      </body>
    </html>
  );
}
